#!/bin/bash
export KUBERNETES_MASTER

set -e

if [[ "$KUBERNETES_MASTER" == *"https"* || "$KUBERNETES_MASTER" == *"443"* ]]; then
  KUBE_TOKEN=$(</var/run/secrets/kubernetes.io/serviceaccount/token)
  MASTER_VERSION=$(curl -sSk -H "Authorization: Bearer $KUBE_TOKEN" $KUBERNETES_MASTER/version |  grep -i gitVersion | grep -o v[0-9]*\\.[0-9]*.\\.[0-9]*)
else
  MASTER_VERSION=$(curl -s $KUBERNETES_MASTER/version |  grep -i gitVersion | grep -o v[0-9]*\\.[0-9]*.\\.[0-9]*)
fi
LOCAL_VERSION=$(kubectl version --client | grep -i gitVersion | grep -o v[0-9]*\\.[0-9]*.\\.[0-9]*)

test "$MASTER_VERSION" == "$LOCAL_VERSION" || ( echo "Client/Server K8S mismatch. Downloading $MASTER_VERSION" &&
  curl -SL https://github.com/kubernetes/kubernetes/releases/download/$MASTER_VERSION/kubernetes.tar.gz \
  | tar xz kubernetes/platforms/linux/amd64/kubectl &&\
  mv kubernetes/platforms/linux/amd64/kubectl /usr/local/bin &&\
  rm -rf kubernetes)

kubectl config set-credentials runner \
  --token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token) 
kubectl config set-cluster openshift \
  --server=$KUBERNETES_MASTER \
  --certificate-authority=/run/secrets/kubernetes.io/serviceaccount/ca.crt
kubectl config set-context me \
  --cluster=openshift \
  --user=runner \
  --namespace=$(cat /run/secrets/kubernetes.io/serviceaccount/namespace)
kubectl config use-context me
